<a href="https://colab.research.google.com/github/prabhu2599/MACHINE-LEARNING-JOURNEY/blob/parallel_roads/Latin_Square.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
arrOld = np.array([[21,14,11,28,18,10],
                [28,33,27,18,24,14],
                [12,31,28,30,17,20],
                [13,24,8,16,24,23],
                [8,11,20,22,24,17],
                [26,13,26,24,19,18]], dtype='int')

In [57]:
arrTk = np.array([[8, 28,21,13,12,26],
                [14,24,31,13,11,33],
                [26,20,27,11,8,28],
                [15,30,24,22,18,28],
                [24,18,24,17,19,24],
                [20,18,17,14,10,23]], dtype='int')

In [31]:
ma = arrOld.max()
mi = arrOld.min()
subt = int(round((ma + mi)/2))
subt

20

In [63]:
arr = arrOld-subt
arrTk = arrTk-subt
arr

array([[  1,  -6,  -9,   8,  -2, -10],
       [  8,  13,   7,  -2,   4,  -6],
       [ -8,  11,   8,  10,  -3,   0],
       [ -7,   4, -12,  -4,   4,   3],
       [-12,  -9,   0,   2,   4,  -3],
       [  6,  -7,   6,   4,  -1,  -2]])

In [42]:
tj = arr.sum(axis=0)
tj

array([-12,   6,   0,  18,   6, -18])

In [43]:
ti = arr.sum(axis=1)
ti

array([-18,  24,  18, -12, -18,   6])

In [44]:
sum([  1,  -6,  -9,   8,  -2, -10])

-18

In [47]:
(tj*tj)/6

array([24.,  6.,  0., 54.,  6., 54.])

In [49]:
sum((tj*tj)/6)

144.0

In [50]:
(ti*ti)/6

array([54., 96., 54., 24., 54.,  6.])

In [51]:
sum((ti*ti)/6)

288.0

In [52]:
arr_square = arr*arr
arr_square

array([[  1,  36,  81,  64,   4, 100],
       [ 64, 169,  49,   4,  16,  36],
       [ 64, 121,  64, 100,   9,   0],
       [ 49,  16, 144,  16,  16,   9],
       [144,  81,   0,   4,  16,   9],
       [ 36,  49,  36,  16,   1,   4]])

In [53]:
E2j = arr_square.sum(axis=0)
E2j

array([358, 472, 374, 204,  62, 158])

In [54]:
sum([64,  784,  441,  169,  144,  676])

2278

In [55]:
E2i = arr_square.sum(axis=1)
E2i

array([286, 338, 358, 250, 254, 142])

In [56]:
print(sum(E2j),sum(E2i))

1628 1628


In [58]:
###################

In [68]:
arrTk

array([[-12,   8,   1,  -7,  -8,   6],
       [ -6,   4,  11,  -7,  -9,  13],
       [  6,   0,   7,  -9, -12,   8],
       [ -5,  10,   4,   2,  -2,   8],
       [  4,  -2,   4,  -3,  -1,   4],
       [  0,  -2,  -3,  -6, -10,   3]])

In [64]:
tik = arrTk.sum(axis=1)
tjk = arrTk.sum(axis=0)
print(tik,tjk)

[-12   6   0  17   6 -18] [-13  18  24 -30 -42  42]


In [65]:
print(sum(tik),sum(tjk))

-1 -1


In [69]:
sum((tjk*tjk)/6)

916.1666666666667

In [71]:
1628-288-144-916.16

279.84000000000003