<a href="https://colab.research.google.com/github/prabhu2599/MACHINE-LEARNING-JOURNEY/blob/parallel_roads/Latin_Square.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
arr = np.array([[8, 28,21,13,12,26],[14,24,31,13,11,33],[26,20,27,11,8,28],[15,30,24,22,18,28],[24,18,24,17,19,24],[20,18,17,14,10,23]], dtype='int')

In [8]:
arr

array([[ 8, 28, 21, 13, 12, 26],
       [14, 24, 31, 13, 11, 33],
       [26, 20, 27, 11,  8, 28],
       [15, 30, 24, 22, 18, 28],
       [24, 18, 24, 17, 19, 24],
       [20, 18, 17, 14, 10, 23]])

In [26]:
tj = arr.sum(axis=0)
(tj*tj)/6

array([1908.16666667, 3174.        , 3456.        , 1350.        ,
       1014.        , 4374.        ])

In [27]:
ti = arr.sum(axis=1)
(ti*ti)/6

array([1944.        , 2646.        , 2400.        , 3128.16666667,
       2646.        , 1734.        ])

In [11]:
sum([ 8, 28, 21, 13, 12, 26])

108

In [28]:
sum((tj*tj)/6)

15276.166666666668

In [29]:
sum((ti*ti)/6)

14498.166666666666

In [30]:
arr_square = arr*arr
arr_square

array([[  64,  784,  441,  169,  144,  676],
       [ 196,  576,  961,  169,  121, 1089],
       [ 676,  400,  729,  121,   64,  784],
       [ 225,  900,  576,  484,  324,  784],
       [ 576,  324,  576,  289,  361,  576],
       [ 400,  324,  289,  196,  100,  529]])

In [32]:
E2j = arr_square.sum(axis=0)
E2j

array([2137, 3308, 3572, 1428, 1114, 4438])

In [36]:
sum([64,  784,  441,  169,  144,  676])

2278

In [37]:
E2i = arr_square.sum(axis=1)
E2i

array([2278, 3112, 2774, 3293, 2702, 1838])

In [38]:
print(sum(E2j),sum(E2i))

15997 15997
